import './globals.css'
import { Manrope } from 'next/font/google'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Advice Generator</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={manrope.className}>{children}</body>
    </html>
  )
}
